//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantLeave
    {
        public int applicantLeaveId { get; set; }
        public Nullable<int> applicantId { get; set; }
        public Nullable<int> leaveTypeId { get; set; }
        public Nullable<System.DateTime> startDated { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string imageLeaveForm { get; set; }
        public string imageAffidavit { get; set; }
        public Nullable<System.DateTime> datedRequested { get; set; }
        public string remarksRequest { get; set; }
        public Nullable<System.DateTime> datedApproval { get; set; }
        public string remarksApproval { get; set; }
        public Nullable<int> noOfDays { get; set; }
        public Nullable<int> approvedBy { get; set; }
        public Nullable<int> requestedBy { get; set; }
        public Nullable<int> approvalStatus { get; set; }
        public string imageMedical { get; set; }
        public string imageMaternity { get; set; }
        public string imagePGAC { get; set; }
        public Nullable<int> ddlDoxTaken { get; set; }
        public string imageForwarding { get; set; }
        public string imageSurety { get; set; }
        public string imageAttorney { get; set; }
        public string imageVisa { get; set; }
        public string imagePurpose { get; set; }
        public Nullable<System.DateTime> edd { get; set; }
        public Nullable<int> approvalBySO { get; set; }
        public Nullable<int> approvalByDS { get; set; }
        public Nullable<int> approvalByAST { get; set; }
        public Nullable<int> approvalBySS { get; set; }
        public Nullable<int> approvalBySec { get; set; }
        public string remarksBySO { get; set; }
        public string remarksByDS { get; set; }
        public string remarksByAST { get; set; }
        public string cnicFrontImage { get; set; }
        public string cnicBackImage { get; set; }
        public Nullable<bool> cnicFrontValidity { get; set; }
        public Nullable<bool> cnicBackValidity { get; set; }
        public Nullable<bool> cnicValidity { get; set; }
        public Nullable<bool> applicationValidity { get; set; }
        public Nullable<bool> affidavitValidity { get; set; }
        public Nullable<bool> medicalValidity { get; set; }
        public Nullable<bool> matenrityValidity { get; set; }
        public Nullable<bool> forwardingValidity { get; set; }
        public Nullable<bool> ipgacValidity { get; set; }
        public Nullable<bool> suretyValidity { get; set; }
        public Nullable<bool> attorneyValidity { get; set; }
        public Nullable<bool> purposeValidity { get; set; }
        public string cnicFrontRemarks { get; set; }
        public string cnicBackRemarks { get; set; }
        public string applicationRemarks { get; set; }
        public string affidavitRemarks { get; set; }
        public string medicalRemarks { get; set; }
        public string matenrityRemarks { get; set; }
        public string forwardingRemarks { get; set; }
        public string ipgacRemarks { get; set; }
        public string suretyRemarks { get; set; }
        public string attorneyRemarks { get; set; }
        public string purposeRemarks { get; set; }
        public Nullable<int> forwardedTo { get; set; }
        public Nullable<bool> visaValidity { get; set; }
        public string visaRemarks { get; set; }
        public string remarksBySS { get; set; }
        public string imageRTMC { get; set; }
        public Nullable<bool> RTMCValidity { get; set; }
        public string RTMCRemarks { get; set; }
        public string imagePreviousLeaveReport { get; set; }
        public Nullable<bool> imagePreviousLeaveReportValidy { get; set; }
        public string imagePreviousLeaveReportRemarks { get; set; }
    }
}
