//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantApprovalStatu
    {
        public int applicationApprovalStatusId { get; set; }
        public int inductionId { get; set; }
        public int phaseId { get; set; }
        public int applicantId { get; set; }
        public int approvalStatusTypeId { get; set; }
        public int approvalStatusId { get; set; }
        public string comments { get; set; }
        public int adminId { get; set; }
        public System.DateTime dated { get; set; }
    }
}
