//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantDebarAmmendment
    {
        public int applicantDebarAmmendmentId { get; set; }
        public Nullable<int> applicantId { get; set; }
        public Nullable<int> inductionId { get; set; }
        public Nullable<int> debarTypeIdOld { get; set; }
        public Nullable<int> debarIdOld { get; set; }
        public Nullable<int> debarTypeId { get; set; }
        public Nullable<int> debarId { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> dated { get; set; }
        public Nullable<int> adminId { get; set; }
    }
}
