//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicationStatusCount
    {
        public int id { get; set; }
        public int inductionId { get; set; }
        public int statusTypeId { get; set; }
        public string statusType { get; set; }
        public int statusId { get; set; }
        public string status { get; set; }
        public int totalCount { get; set; }
    }
}
