//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantVoucher
    {
        public int applicantVoucherId { get; set; }
        public int inductionId { get; set; }
        public int phaseId { get; set; }
        public int applicantId { get; set; }
        public int amount { get; set; }
        public string branchCode { get; set; }
        public string voucherImage { get; set; }
        public string ibn { get; set; }
        public string accountNo { get; set; }
        public string accountTitle { get; set; }
        public System.DateTime submittedDate { get; set; }
        public System.DateTime dated { get; set; }
    }
}
