//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantExtensionCorrespondence
    {
        public int extensionCorrespondenceId { get; set; }
        public Nullable<int> applicantExtensionId { get; set; }
        public Nullable<int> correspondenceFrom { get; set; }
        public Nullable<int> correspondenceTo { get; set; }
        public string remarks { get; set; }
        public string imageApplication { get; set; }
        public string imagePER { get; set; }
        public string imageNOC { get; set; }
        public string imagePMDC { get; set; }
        public string imageExtensionOrder { get; set; }
        public string imageJoiningOrder { get; set; }
        public string imageDoc1 { get; set; }
        public string imageDoc2 { get; set; }
        public string imageInductionOrder { get; set; }
        public string rtmcUhsNo { get; set; }
        public string imageTothc { get; set; }
        public string imageJoat { get; set; }
        public Nullable<bool> imageApplicationValidity { get; set; }
        public Nullable<bool> imagePERValidity { get; set; }
        public Nullable<bool> imageNOCValidity { get; set; }
        public Nullable<bool> imagePMDCValidity { get; set; }
        public Nullable<bool> imageExtensionOrderValidity { get; set; }
        public Nullable<bool> imageJoiningOrderValidity { get; set; }
        public Nullable<bool> imageDoc1Validity { get; set; }
        public Nullable<bool> imageDoc2Validity { get; set; }
        public Nullable<bool> imageInductionOrderValidity { get; set; }
        public Nullable<bool> rtmcUhsNoValidity { get; set; }
        public Nullable<bool> imageTothcValidity { get; set; }
        public Nullable<bool> imageJoatValidity { get; set; }
        public string imageApplicationRemarks { get; set; }
        public string imagePERRemarks { get; set; }
        public string imageNOCRemarks { get; set; }
        public string imagePMDCRemarks { get; set; }
        public string imageExtensionOrderRemarks { get; set; }
        public string imageJoiningOrderRemarks { get; set; }
        public string imageDoc1Remarks { get; set; }
        public string imageDoc2Remarks { get; set; }
        public string imageInductionOrderRemarks { get; set; }
        public string rtmcUhsNoRemarks { get; set; }
        public string imageTothcRemarks { get; set; }
        public string imageJoatRemarks { get; set; }
        public Nullable<int> noOfMonths { get; set; }
        public Nullable<int> actionPerformed { get; set; }
        public Nullable<System.DateTime> dated { get; set; }
        public Nullable<int> adminId { get; set; }
        public Nullable<int> applicantId { get; set; }
    }
}
