//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantExperienceBK
    {
        public int applicantExperienceId { get; set; }
        public int applicantId { get; set; }
        public int levelId { get; set; }
        public int levelTypeId { get; set; }
        public string instituteName { get; set; }
        public int instituteId { get; set; }
        public int provinceId { get; set; }
        public int typeId { get; set; }
        public System.DateTime startDated { get; set; }
        public System.DateTime endDate { get; set; }
        public int noOfMonth { get; set; }
        public int noOfDays { get; set; }
        public bool isCurrent { get; set; }
        public string imageExperience { get; set; }
        public System.DateTime dated { get; set; }
    }
}
