//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantExtension_deleted
    {
        public int applicantExtensionId { get; set; }
        public Nullable<int> applicantId { get; set; }
        public Nullable<System.DateTime> startDated { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> noOfDays { get; set; }
        public Nullable<int> noOfMonths { get; set; }
        public Nullable<int> approvalBySupervisor { get; set; }
        public string imageApplication { get; set; }
        public string imagePER { get; set; }
        public string imageNOC { get; set; }
        public string imagePMDC { get; set; }
        public string imageExtensionOrder { get; set; }
        public string imageJoiningOrder { get; set; }
        public string imageDoc1 { get; set; }
        public string imageDoc2 { get; set; }
        public Nullable<int> requestedBy { get; set; }
        public Nullable<System.DateTime> datedRequested { get; set; }
        public string remarksRequested { get; set; }
        public Nullable<int> approvalStatus { get; set; }
        public Nullable<int> approvedBy { get; set; }
        public Nullable<System.DateTime> datedApproval { get; set; }
        public string remarksApproval { get; set; }
        public string imageInductionOrder { get; set; }
        public string rtmcUhsNo { get; set; }
        public string imageTothc { get; set; }
        public string imageJoat { get; set; }
    }
}
