//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantDistinctionFinal
    {
        public int applicantDistinctionId { get; set; }
        public int inductionId { get; set; }
        public int phaseId { get; set; }
        public int applicantId { get; set; }
        public string subject { get; set; }
        public int year { get; set; }
        public string imageDistinction { get; set; }
        public System.DateTime dated { get; set; }
    }
}
