//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantQuota
    {
        public int applicantQuotaId { get; set; }
        public int applicantId { get; set; }
        public int quotaId { get; set; }
        public int inductionId { get; set; }
    }
}
