//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantDegreeMark
    {
        public int degreeMarksId { get; set; }
        public int inductionId { get; set; }
        public int phaseId { get; set; }
        public int applicantId { get; set; }
        public int graduateTypeId { get; set; }
        public int year { get; set; }
        public decimal totalMarks { get; set; }
        public decimal obtainMarks { get; set; }
        public decimal marksPercentage { get; set; }
        public int attempt { get; set; }
        public string imageDMC { get; set; }
        public Nullable<int> position { get; set; }
        public string imagePosition { get; set; }
        public bool isActive { get; set; }
        public decimal marks { get; set; }
    }
}
