//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantHouseJobDetail
    {
        public int jobDetailId { get; set; }
        public int inductionId { get; set; }
        public int applicantId { get; set; }
        public int instituteTypeId { get; set; }
        public int degreeProviceId { get; set; }
        public int houseJobProvideId { get; set; }
        public int noOfDays { get; set; }
        public int isSame { get; set; }
        public int houseJobTypeId { get; set; }
        public int marksType { get; set; }
        public decimal marks { get; set; }
        public int adminId { get; set; }
        public System.DateTime dated { get; set; }
    }
}
