//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantSpecialityInstituteQuotaMark
    {
        public int id { get; set; }
        public int applicantId { get; set; }
        public int specialityJobId { get; set; }
        public int quotaId { get; set; }
        public int typeId { get; set; }
        public int specialityId { get; set; }
        public int instituteId { get; set; }
        public int hospitalId { get; set; }
        public int hospitalInstituteId { get; set; }
        public int prefferenceId { get; set; }
        public int prefferenceNo { get; set; }
        public decimal programMarks { get; set; }
        public decimal instituteMarks { get; set; }
    }
}
