//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantHouseJobMark
    {
        public int id { get; set; }
        public int applicantId { get; set; }
        public int noOfRows { get; set; }
        public int noOfDays { get; set; }
        public bool isSame { get; set; }
        public int countryId { get; set; }
        public int noOfProvince { get; set; }
        public int provinceId { get; set; }
        public int marksType { get; set; }
        public decimal marks { get; set; }
    }
}
