//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantJoinedPreviou
    {
        public Nullable<double> applicantIdOld { get; set; }
        public string name { get; set; }
        public string pmdcNo { get; set; }
        public Nullable<double> cellNumber { get; set; }
        public Nullable<double> Preference { get; set; }
        public int SpecialtyId { get; set; }
        public string Specialty { get; set; }
        public Nullable<int> ProgramId { get; set; }
        public string Program { get; set; }
        public int hospitalId { get; set; }
        public string Institute { get; set; }
        public Nullable<double> Aggregate { get; set; }
        public Nullable<System.DateTime> Induction { get; set; }
        public int inductionId { get; set; }
        public string joiningStatus { get; set; }
        public bool isActive { get; set; }
        public System.DateTime dated { get; set; }
        public int applicantId { get; set; }
    }
}
