//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAppData
    {
        public int applicantId { get; set; }
        public string name { get; set; }
        public string pmdcNo { get; set; }
        public string cellNo { get; set; }
        public int hospitalId { get; set; }
        public string hospital { get; set; }
        public int typeId { get; set; }
        public string type { get; set; }
        public string joiningdate { get; set; }
        public System.DateTime dateJoining { get; set; }
        public int inductionId { get; set; }
    }
}
