//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicantDoc
    {
        public int applicantDocId { get; set; }
        public int applicantId { get; set; }
        public string profile { get; set; }
        public string cnicFront { get; set; }
        public string cnicBack { get; set; }
        public string domicileFront { get; set; }
        public string domicileBack { get; set; }
    
        public virtual tblApplicant tblApplicant { get; set; }
    }
}
