//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactAttendence
    {
        public int contactIdAttendenceId { get; set; }
        public int contactId { get; set; }
        public int inductionId { get; set; }
        public int applicantId { get; set; }
        public int isSelf { get; set; }
        public int relationId { get; set; }
        public int attendenceNo { get; set; }
        public System.DateTime dated { get; set; }
        public int adminId { get; set; }
    }
}
