//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCalendar
    {
        public int calendarId { get; set; }
        public int inductionId { get; set; }
        public string title { get; set; }
        public int typeId { get; set; }
        public System.DateTime dateExpire { get; set; }
        public bool isActive { get; set; }
        public System.DateTime dated { get; set; }
    }
}
