//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactDoc
    {
        public int contactDocsId { get; set; }
        public int contactId { get; set; }
        public string image { get; set; }
        public int typeId { get; set; }
    }
}
