//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmailProcess
    {
        public int emailProcessId { get; set; }
        public int emailTemplateId { get; set; }
        public int applicantId { get; set; }
        public int typeId { get; set; }
        public int inductionId { get; set; }
        public string body { get; set; }
        public int isProcess { get; set; }
        public int isSent { get; set; }
        public System.DateTime dated { get; set; }
        public int adminId { get; set; }
    }
}
