//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmail
    {
        public int id { get; set; }
        public string emailId { get; set; }
        public string password { get; set; }
        public int typeId { get; set; }
        public int limit { get; set; }
        public bool isActive { get; set; }
        public System.DateTime dated { get; set; }
    }
}
