//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int employeeId { get; set; }
        public string name { get; set; }
        public int genderId { get; set; }
        public int relationId { get; set; }
        public string relationName { get; set; }
        public int martialStatusId { get; set; }
        public string cellNo { get; set; }
        public string cnic { get; set; }
        public int districtId { get; set; }
        public string address { get; set; }
        public int designationId { get; set; }
        public int degreeId { get; set; }
        public int hospitalId { get; set; }
        public System.DateTime joiningDate { get; set; }
        public string image { get; set; }
        public int yearExerience { get; set; }
        public string programIds { get; set; }
        public bool isActive { get; set; }
        public int adminId { get; set; }
        public System.DateTime dated { get; set; }
        public string rtmcNumber { get; set; }
        public string imageRTMC { get; set; }
        public Nullable<int> statusApproval { get; set; }
        public string uhsNumber { get; set; }
        public string imageUHS { get; set; }
        public Nullable<int> statusApprovalUHS { get; set; }
    }
}
