//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExperienceMarksBk
    {
        public int id { get; set; }
        public int applicantExperienceId { get; set; }
        public int applicantId { get; set; }
        public int levelId { get; set; }
        public int typeId { get; set; }
        public int provinceId { get; set; }
        public System.DateTime startDateOld { get; set; }
        public System.DateTime endDateOld { get; set; }
        public int noOfMonthOld { get; set; }
        public int rowNum { get; set; }
        public int rnk { get; set; }
        public int rowNumRank { get; set; }
        public int dayDiff { get; set; }
        public int diffType { get; set; }
        public string mapContinuousId { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int noOfMonth { get; set; }
        public int rowNumContinuous { get; set; }
        public decimal marks { get; set; }
    }
}
