//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeedBack
    {
        public int feedbackId { get; set; }
        public int applicantIdBy { get; set; }
        public string pmdcNo { get; set; }
        public string comments { get; set; }
        public System.DateTime dated { get; set; }
        public int adminId { get; set; }
        public string reply { get; set; }
        public System.DateTime datedReply { get; set; }
    }
}
