//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGrievanceAction
    {
        public int grievanceActionId { get; set; }
        public int grievanceId { get; set; }
        public int isSelf { get; set; }
        public int relationId { get; set; }
        public int attendenceNo { get; set; }
        public System.DateTime datedAttendece { get; set; }
        public int adminIdAttendece { get; set; }
        public int actionId { get; set; }
        public int adminIdAction { get; set; }
        public System.DateTime dateAction { get; set; }
    }
}
