//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGazetteDetail
    {
        public int gazetteId { get; set; }
        public int applicantId { get; set; }
        public int typeId { get; set; }
        public decimal matric { get; set; }
        public decimal fsc { get; set; }
        public decimal degree { get; set; }
        public decimal attempts { get; set; }
        public decimal houseJob { get; set; }
        public decimal experience { get; set; }
        public decimal research { get; set; }
        public decimal position { get; set; }
        public decimal marksProgram { get; set; }
        public decimal marksTotal { get; set; }
    }
}
