//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGazatFCPSD
    {
        public int gazatId { get; set; }
        public int applicantId { get; set; }
        public int preferenceNo { get; set; }
        public decimal marks { get; set; }
        public int sequence { get; set; }
        public int specialityJobId { get; set; }
        public int seats { get; set; }
        public int noOfDays { get; set; }
        public int extraId { get; set; }
    }
}
