//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHsStepCalendar
    {
        public int id { get; set; }
        public int hsId { get; set; }
        public int stepId { get; set; }
        public System.DateTime startDate { get; set; }
        public int startH { get; set; }
        public int startM { get; set; }
        public System.DateTime endDate { get; set; }
        public int endH { get; set; }
        public int endM { get; set; }
        public string duration { get; set; }
        public int statusId { get; set; }
        public System.DateTime dated { get; set; }
        public int adminId { get; set; }
    }
}
