//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHospital
    {
        public int hospitalId { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string abbr { get; set; }
        public string nameDisplay { get; set; }
        public int regionId { get; set; }
        public int levelId { get; set; }
        public int typeId { get; set; }
        public bool isActive { get; set; }
        public string address { get; set; }
        public System.DateTime dated { get; set; }
        public int adminId { get; set; }
    }
}
