//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInduction
    {
        public int inductionId { get; set; }
        public string name { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public bool isCompleted { get; set; }
        public int isActive { get; set; }
        public bool status { get; set; }
        public System.DateTime dated { get; set; }
        public int adminId { get; set; }
    }
}
