//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInductionCalendar
    {
        public int id { get; set; }
        public int levelId { get; set; }
        public int inductionId { get; set; }
        public int calenderId { get; set; }
        public int days { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int statusId { get; set; }
        public System.DateTime dated { get; set; }
        public int adminId { get; set; }
    }
}
