//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobKey
    {
        public int jobKeyId { get; set; }
        public int projId { get; set; }
        public int quotaId { get; set; }
        public int typeId { get; set; }
        public int specialityId { get; set; }
        public int superSpecialityId { get; set; }
        public int instituteId { get; set; }
        public int hospitalId { get; set; }
        public string key { get; set; }
        public string quotaName { get; set; }
        public string typeName { get; set; }
        public string specialityName { get; set; }
        public string superSpecialityName { get; set; }
        public string instituteName { get; set; }
        public string hospitalName { get; set; }
    }
}
