//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeave
    {
        public int leaveId { get; set; }
        public int hospitalId { get; set; }
        public int applicantId { get; set; }
        public int typeId { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int noOfDays { get; set; }
        public int assignBy { get; set; }
        public int assignTo { get; set; }
        public int statusId { get; set; }
        public string remarks { get; set; }
        public System.DateTime dated { get; set; }
        public int adminId { get; set; }
    }
}
