//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMeritRangeFCPSD
    {
        public int idMinMax { get; set; }
        public int roundNo { get; set; }
        public int specialityJobId { get; set; }
        public decimal minMerit { get; set; }
        public decimal maxMerit { get; set; }
        public System.DateTime dated { get; set; }
    }
}
