//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMeritApplicantFinal
    {
        public int meritApplicantId { get; set; }
        public int inductionId { get; set; }
        public int phaseId { get; set; }
        public int typeId { get; set; }
        public int applicantId { get; set; }
        public decimal marks { get; set; }
        public int preferenceNo { get; set; }
        public int noOfDays { get; set; }
        public int specialityJobId { get; set; }
        public int roundNo { get; set; }
    }
}
