//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenuUser
    {
        public int menuUserId { get; set; }
        public int menuId { get; set; }
        public int userId { get; set; }
    
        public virtual tblMenu tblMenu { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
