//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMarksApplicantDetail
    {
        public int id { get; set; }
        public int applicantId { get; set; }
        public decimal degree { get; set; }
        public decimal attempts { get; set; }
        public decimal houseJob { get; set; }
        public decimal experience { get; set; }
        public decimal research { get; set; }
        public decimal marks { get; set; }
        public System.DateTime dated { get; set; }
    }
}
