//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResignation
    {
        public int resignationId { get; set; }
        public int applicantId { get; set; }
        public int specialityJobId { get; set; }
        public System.DateTime resignationDate { get; set; }
        public string image { get; set; }
        public bool isActive { get; set; }
        public System.DateTime dated { get; set; }
        public int adminId { get; set; }
    }
}
