//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResearchJournalsData
    {
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string batch { get; set; }
        public string country { get; set; }
        public string displine { get; set; }
    }
}
