//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVfCheckApplicant
    {
        public int id { get; set; }
        public int projId { get; set; }
        public int inductionId { get; set; }
        public int applicantId { get; set; }
        public int vfcheckId { get; set; }
        public int detailId { get; set; }
        public string table { get; set; }
        public string comments { get; set; }
        public bool isActive { get; set; }
        public System.DateTime dated { get; set; }
        public int adminId { get; set; }
    }
}
