//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwApplicantFinal
    {
        public int applicantIdFinal { get; set; }
        public int inductionId { get; set; }
        public int phaseId { get; set; }
        public int typeId { get; set; }
        public int applicantId { get; set; }
        public decimal marks { get; set; }
        public int preferenceNo { get; set; }
        public int specialityJobId { get; set; }
        public bool isManual { get; set; }
        public string specialityName { get; set; }
        public string instituteName { get; set; }
        public string hospitalName { get; set; }
        public string quotaName { get; set; }
        public string typeName { get; set; }
        public int specialityId { get; set; }
        public int hospitalId { get; set; }
        public int instituteId { get; set; }
        public int quotaId { get; set; }
    }
}
