//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwApplicantInfoDualNational
    {
        public int dualInfoId { get; set; }
        public int applicantId { get; set; }
        public int countryId { get; set; }
        public string countryName { get; set; }
        public string embassyCertificate { get; set; }
        public string languageCertificate { get; set; }
        public string policeCertificate { get; set; }
        public string affidavitCertificate { get; set; }
        public System.DateTime dated { get; set; }
        public int adminId { get; set; }
    }
}
