//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwApplicantCertificate
    {
        public int applicantCertificateTypeId { get; set; }
        public int inductionId { get; set; }
        public int phaseId { get; set; }
        public int applicantId { get; set; }
        public int typeId { get; set; }
        public string typeName { get; set; }
        public int disciplineId { get; set; }
        public string disciplineName { get; set; }
        public int obtainMarks { get; set; }
        public int totalMarks { get; set; }
        public System.DateTime passingDate { get; set; }
        public string imageCertificate { get; set; }
        public System.DateTime dated { get; set; }
    }
}
