//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwApplicantSpecialityInstitute
    {
        public int applicantId { get; set; }
        public int instituteId { get; set; }
        public int hospitalId { get; set; }
        public int instituteIdO { get; set; }
        public int hospitalIdO { get; set; }
        public int markRatio { get; set; }
    }
}
