//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwApplicationAmendment
    {
        public int applicantId { get; set; }
        public string name { get; set; }
        public string pmdcNo { get; set; }
        public string contactNumber { get; set; }
        public int countryId { get; set; }
        public string countryName { get; set; }
        public int countryTypeId { get; set; }
        public int countryIdDegreePassing { get; set; }
        public string countryDegreePassing { get; set; }
        public int degreeCountryTypeId { get; set; }
        public string status { get; set; }
        public int statusId { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> dated { get; set; }
        public string adminName { get; set; }
    }
}
