//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwApplicantNew
    {
        public Nullable<int> inductionId { get; set; }
        public int applicantId { get; set; }
        public string name { get; set; }
        public string pmdcNo { get; set; }
        public string emailId { get; set; }
        public string password { get; set; }
        public string passwordDecrypt { get; set; }
        public string contactNumber { get; set; }
        public int network { get; set; }
        public string pic { get; set; }
        public string date { get; set; }
        public int facultyId { get; set; }
        public string facultyName { get; set; }
        public int accountStatusId { get; set; }
        public string accountStatus { get; set; }
    }
}
