//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwApplicationStatusLog
    {
        public int applicantId { get; set; }
        public string name { get; set; }
        public string pmdcNo { get; set; }
        public string contactNumber { get; set; }
        public string emailId { get; set; }
        public string status { get; set; }
        public int applicationStatusId { get; set; }
        public System.DateTime dated { get; set; }
    }
}
