//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwBed
    {
        public int bedId { get; set; }
        public int inductionId { get; set; }
        public string induction { get; set; }
        public int hospitalId { get; set; }
        public string hospital { get; set; }
        public int departmentId { get; set; }
        public string department { get; set; }
        public int unitId { get; set; }
        public string unit { get; set; }
        public int disciplineId { get; set; }
        public string discipline { get; set; }
        public string speciality { get; set; }
        public int bedsER { get; set; }
        public int bedsICU { get; set; }
        public int bedsOther { get; set; }
        public int bedsWards { get; set; }
        public int adminId { get; set; }
        public string admin { get; set; }
        public System.DateTime dated { get; set; }
        public string remarksN { get; set; }
        public string imageN { get; set; }
        public int bedsDep { get; set; }
        public string remarksDep { get; set; }
        public string imageDep { get; set; }
        public int specialityId { get; set; }
    }
}
