//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwContact
    {
        public int contactId { get; set; }
        public int inductionId { get; set; }
        public string name { get; set; }
        public int applicantId { get; set; }
        public string pmdcNo { get; set; }
        public string emailId { get; set; }
        public string title { get; set; }
        public string question { get; set; }
        public System.DateTime dated { get; set; }
        public int typeId { get; set; }
        public string typeName { get; set; }
        public int assignToId { get; set; }
        public string assignTo { get; set; }
        public int recievedDocs { get; set; }
        public int totalReply { get; set; }
        public int sentDocs { get; set; }
    }
}
