//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwConstant
    {
        public int constantId { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public int value { get; set; }
        public string nameDisplay { get; set; }
        public string shortDesc { get; set; }
        public string detail { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public int parentId { get; set; }
        public int typeId { get; set; }
        public System.DateTime dated { get; set; }
        public int adminId { get; set; }
        public string typeName { get; set; }
    }
}
