//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwEmailProcessCount
    {
        public int typeId { get; set; }
        public string type { get; set; }
        public int isProcess { get; set; }
        public int isSent { get; set; }
        public int inductionId { get; set; }
    }
}
