//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwEmailTemplate
    {
        public int emailTemplateId { get; set; }
        public int inductionId { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public string subject { get; set; }
        public string body { get; set; }
        public int typeId { get; set; }
        public bool isActive { get; set; }
        public int adminId { get; set; }
        public System.DateTime dated { get; set; }
        public string typeName { get; set; }
    }
}
