//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwfApplicantResearchPaper
    {
        public int applicantResearchId { get; set; }
        public int inductionId { get; set; }
        public int phaseId { get; set; }
        public int applicantId { get; set; }
        public string name { get; set; }
        public int authorId { get; set; }
        public int publishStatusId { get; set; }
        public string link { get; set; }
        public string imageLetter { get; set; }
        public System.DateTime dated { get; set; }
        public string author { get; set; }
        public string publishStatus { get; set; }
        public int researchJournalId { get; set; }
        public string researchJournalName { get; set; }
        public string typeName { get; set; }
        public string batch { get; set; }
        public string regionName { get; set; }
        public string displine { get; set; }
        public int typeId { get; set; }
        public int batchId { get; set; }
        public int regionId { get; set; }
        public int displineId { get; set; }
    }
}
