//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwFeedback
    {
        public int feedbackId { get; set; }
        public int feedBackById { get; set; }
        public string feedBackByPmdcNo { get; set; }
        public string feedBackByEmailId { get; set; }
        public string feedBackByContactNumber { get; set; }
        public System.DateTime dated { get; set; }
        public string comments { get; set; }
        public int adminId { get; set; }
        public string reply { get; set; }
        public System.DateTime datedReply { get; set; }
        public int feedBackTypeId { get; set; }
        public string feedBackTypeName { get; set; }
        public string name { get; set; }
        public string pmdcNo { get; set; }
        public string emailId { get; set; }
        public string contactNumber { get; set; }
    }
}
