//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwfApplicantInfo
    {
        public int applicantDetailId { get; set; }
        public int inductionId { get; set; }
        public int phaseId { get; set; }
        public int applicantId { get; set; }
        public string fatherName { get; set; }
        public System.DateTime dob { get; set; }
        public int genderId { get; set; }
        public string gender { get; set; }
        public int disableId { get; set; }
        public string disable { get; set; }
        public System.DateTime pmdcExpiryDate { get; set; }
        public int countryIdDegreePassing { get; set; }
        public string countryDegreePassing { get; set; }
        public System.DateTime mbbsPassingDate { get; set; }
        public int countryId { get; set; }
        public string countryName { get; set; }
        public int districtId { get; set; }
        public string districtName { get; set; }
        public string address { get; set; }
        public int domicileProvinceId { get; set; }
        public string domicileProvince { get; set; }
        public string domicilePicFront { get; set; }
        public string domicilePicBack { get; set; }
        public int domicileDistrictId { get; set; }
        public string domicileDistrict { get; set; }
        public string cnicNo { get; set; }
        public System.DateTime cnicExpiryDate { get; set; }
        public string cnicPicFront { get; set; }
        public string cnicPicBack { get; set; }
        public string disableImage { get; set; }
    }
}
