//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwFrontDesk
    {
        public int fdId { get; set; }
        public string name { get; set; }
        public string contactNo { get; set; }
        public string emailId { get; set; }
        public string info { get; set; }
        public string title { get; set; }
        public string question { get; set; }
        public int deptId { get; set; }
        public int projId { get; set; }
        public int assignToId { get; set; }
        public System.DateTime dated { get; set; }
        public int adminId { get; set; }
        public string proj { get; set; }
        public string admin { get; set; }
        public string assignTo { get; set; }
        public string dept { get; set; }
    }
}
