//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwfApplicantDegree
    {
        public int applicantDegreeDetailId { get; set; }
        public int inductionId { get; set; }
        public int phaseId { get; set; }
        public int applicantId { get; set; }
        public int graduateTypeId { get; set; }
        public int degreeTypeId { get; set; }
        public int degreeYear { get; set; }
        public int instituteTypeId { get; set; }
        public int instituteId { get; set; }
        public string instituteName { get; set; }
        public int totalMarks { get; set; }
        public int obtainMarks { get; set; }
        public string imageDegree { get; set; }
        public string imageDegreeForeignFront { get; set; }
        public string imageDegreeForeignBack { get; set; }
        public int houseJobTypeId { get; set; }
        public string instituteHouseJob { get; set; }
        public int provinceIdHouseJob { get; set; }
        public string imageHouseJob { get; set; }
        public string imageDegreeMatric { get; set; }
        public string imageCertificate { get; set; }
        public System.DateTime dated { get; set; }
        public string graduateType { get; set; }
        public string degree { get; set; }
        public string instituteType { get; set; }
        public string instituteNameThis { get; set; }
        public string provinceHouseJob { get; set; }
        public string houseJobType { get; set; }
        public bool houseJobIsSameInstitute { get; set; }
    }
}
