//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwGazetteDetail
    {
        public int applicantId { get; set; }
        public string name { get; set; }
        public string fatherName { get; set; }
        public string pmdcNo { get; set; }
        public string emailId { get; set; }
        public string contactNumber { get; set; }
        public int quotaId { get; set; }
        public string quotaName { get; set; }
        public int typeId { get; set; }
        public string typeName { get; set; }
        public decimal degree { get; set; }
        public decimal attempts { get; set; }
        public decimal houseJob { get; set; }
        public decimal experience { get; set; }
        public decimal research { get; set; }
        public decimal marksProgram { get; set; }
        public Nullable<decimal> position { get; set; }
        public Nullable<decimal> matric { get; set; }
        public Nullable<decimal> fsc { get; set; }
        public decimal marksTotal { get; set; }
        public string researchLinks { get; set; }
    }
}
