//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwGazat
    {
        public Nullable<int> quotaId { get; set; }
        public string quotaName { get; set; }
        public int typeId { get; set; }
        public string typeName { get; set; }
        public string name { get; set; }
        public string fatherName { get; set; }
        public string pmdcNo { get; set; }
        public string emailId { get; set; }
        public Nullable<decimal> marks { get; set; }
        public int applicantId { get; set; }
    }
}
