//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwHsApplication
    {
        public int hsAppId { get; set; }
        public int hsId { get; set; }
        public int typeId { get; set; }
        public int applicantId { get; set; }
        public string detail { get; set; }
        public int specialityJobId { get; set; }
        public int statusId { get; set; }
        public System.DateTime dated { get; set; }
        public string typeName { get; set; }
    }
}
