//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwInductionYear
    {
        public int yearId { get; set; }
        public string yearName { get; set; }
        public int inductionId { get; set; }
        public string inductionName { get; set; }
    }
}
