//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwLeaveApplicantStatusCount
    {
        public int applicantId { get; set; }
        public Nullable<int> leavePending { get; set; }
        public Nullable<int> leaveAccepted { get; set; }
        public Nullable<int> leaveRejected { get; set; }
        public Nullable<int> leaveCancelled { get; set; }
    }
}
