//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwMenu
    {
        public int menuId { get; set; }
        public string name { get; set; }
        public string nameDisplay { get; set; }
        public string url { get; set; }
        public string iconClass { get; set; }
        public int sortOrder { get; set; }
        public bool isMenu { get; set; }
        public bool isActive { get; set; }
        public int parentId { get; set; }
        public int typeId { get; set; }
        public System.DateTime dated { get; set; }
        public int adminId { get; set; }
        public string typeName { get; set; }
        public int appId { get; set; }
        public string appName { get; set; }
        public string parentName { get; set; }
        public string adminName { get; set; }
    }
}
