//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwRemaningJobsSpecialityFCP
    {
        public int specialityJobId { get; set; }
        public int seats { get; set; }
        public int seatsFilled { get; set; }
        public Nullable<int> seatsRemaining { get; set; }
    }
}
