//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwSmsProcess
    {
        public int smsProcessId { get; set; }
        public int isProcess { get; set; }
        public string process { get; set; }
        public int isSent { get; set; }
        public string sent { get; set; }
        public int applicantId { get; set; }
        public System.DateTime dated { get; set; }
        public int smsId { get; set; }
        public string detail { get; set; }
        public int typeId { get; set; }
        public string typeName { get; set; }
        public int inductionid { get; set; }
    }
}
