//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvwVoucherBankInfo
    {
        public int inductionId { get; set; }
        public int phaseId { get; set; }
        public int applicantId { get; set; }
        public string name { get; set; }
        public string pmdcNo { get; set; }
        public string contactNumber { get; set; }
        public string emailId { get; set; }
        public int amount { get; set; }
        public string transactionIdBank { get; set; }
        public int statusBank { get; set; }
        public string statusBankName { get; set; }
        public int transactionType { get; set; }
        public System.DateTime bankDated { get; set; }
        public int statusId { get; set; }
        public string status { get; set; }
    }
}
